version: "2"
linters:
  default: all
  disable:
    - cyclop
    - err113
    - errcheck
    - exhaustruct
    - exhaustruct_v5
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gomodguard
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - sqlclosecheck
    - testableexamples
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/xo/dburl
    gosec:
      excludes:
        - G101
        - G304
    gocritic:
      disabled-checks:
        - exitAfterDefer
